
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildozer
        uses: ArtemGovorov/buildozer-action@v1.2

      - name: Build APK
        run: buildozer android debug
